### ISSUE TITLE
Crashes when using the EmuColorPicker Class

### ISSUE THREAD

**Issue by Juiin** [DragoniteSpam/Emu#5]
Here are some crashes i encountered when experimenting with the EmuColorPicker Class:

When Clicking on a Color Picker, code used from the Wiki Example:

Variable <unknown_object>.controls(102449, -2147483648) not set before reading it.
 at gml_Script_anon_EmuColorPicker_gml_GlobalScript_EmuInput_ColorPicker_1069_EmuColorPicker_gml_GlobalScript_EmuInput_ColorPicker (line 319) -                     dialog.el_picker = new controls(32, EMU_AUTO, ew, eh, value, _allow_alpha, function() {
############################################################################################
gml_Script_anon_EmuColorPicker_gml_GlobalScript_EmuInput_ColorPicker_1069_EmuColorPicker_gml_GlobalScript_EmuInput_ColorPicker (line 319)
gml_Script_anon_EmuCore_gml_GlobalScript_Emu_Core_3104_EmuCore_gml_GlobalScript_Emu_Core (line 107) -             if (_contents[| i]) _contents[| i].Render(at_x, at_y);
gml_Script_anon_EmuCore_gml_GlobalScript_Emu_Core_2870_EmuCore_gml_GlobalScript_Emu_Core (line 102) -         renderContents(x + base_x, y + base_y);
gml_Object_oCharSheet_Draw_64 (line 1) - container.Render();

When closing an Overlay containing a Color Picker:

Variable EmuColorPicker._surface(100615, -2147483648) not set before reading it.
 at gml_Script_anon_EmuColorPicker_gml_GlobalScript_EmuInput_ColorPicker_19158_EmuColorPicker_gml_GlobalScript_EmuInput_ColorPicker (line 351) -         if (surface_exists(_surface)) surface_free(_surface);
############################################################################################
gml_Script_anon_EmuColorPicker_gml_GlobalScript_EmuInput_ColorPicker_19158_EmuColorPicker_gml_GlobalScript_EmuInput_ColorPicker (line 351)
gml_Script_anon_EmuCore_gml_GlobalScript_Emu_Core_3875_EmuCore_gml_GlobalScript_Emu_Core (line 134) -             _contents[| i].Destroy();
gml_Script_anon_EmuCore_gml_GlobalScript_Emu_Core_3800_EmuCore_gml_GlobalScript_Emu_Core (line 128) -         destroyContent();
gml_Script_anon_EmuDialog_gml_GlobalScript_EmuDialog_937_EmuDialog_gml_GlobalScript_EmuDialog (line 38) -             top.Destroy();
gml_Script_anon_EmuDialog_gml_GlobalScript_EmuDialog_303_EmuDialog_gml_GlobalScript_EmuDialog (line 8) -     SetCallback(function() { Close(); });
gml_Script_anon_EmuDialog_gml_GlobalScript_EmuDialog_1313_EmuDialog_gml_GlobalScript_EmuDialog (line 132) -             callback();
gml_Script_anon_EmuCore_gml_GlobalScript_Emu_Core_3104_EmuCore_gml_GlobalScript_Emu_Core (line 107) -             if (_contents[| i]) _contents[| i].Render(at_x, at_y);
gml_Script_anon_EmuCore_gml_GlobalScript_Emu_Core_2870_EmuCore_gml_GlobalScript_Emu_Core (line 102) -         renderContents(x + base_x, y + base_y);
gml_Object_obj_emu_demo_Draw_0 (line 2) - EmuOverlay.Render();

Also one little thing i noticed, at EmuInput Line 133&134 the Line is duplicated both are surface_set_target(_surface);

**Comment by DragoniteSpam** [comment]
Interesting, turns out there were a few different things wrong with the color pickers. Should be fixed now on [Itch](https://dragonite.itch.io/emu-ui-for-gamemaker), thanks for letting me know.
