### ISSUE TITLE
Crash when closing a Dialog containing an EmuList

### ISSUE THREAD

**Issue by Juiin** [DragoniteSpam/Emu#7]
Code used from the Example Section on EmuList on the Wiki:

Variable EmuList.own_entries(102128, -2147483648) not set before reading it.
 at gml_Script_anon_EmuList_gml_GlobalScript_EmuList_15380_EmuList_gml_GlobalScript_EmuList (line 370) -         if (own_entries) ds_list_destroy(_entries);
############################################################################################
gml_Script_anon_EmuList_gml_GlobalScript_EmuList_15380_EmuList_gml_GlobalScript_EmuList (line 370)
gml_Script_anon_EmuCore_gml_GlobalScript_Emu_Core_3875_EmuCore_gml_GlobalScript_Emu_Core (line 134) -             _contents[| i].Destroy();
gml_Script_anon_EmuCore_gml_GlobalScript_Emu_Core_3800_EmuCore_gml_GlobalScript_Emu_Core (line 128) -         destroyContent();
gml_Script_anon_EmuDialog_gml_GlobalScript_EmuDialog_937_EmuDialog_gml_GlobalScript_EmuDialog (line 38) -             top.Destroy();
gml_Script_anon_EmuDialog_gml_GlobalScript_EmuDialog_303_EmuDialog_gml_GlobalScript_EmuDialog (line 8) -     SetCallback(function() { Close(); });
gml_Script_anon_EmuDialog_gml_GlobalScript_EmuDialog_1313_EmuDialog_gml_GlobalScript_EmuDialog (line 132) -             callback();
gml_Script_anon_EmuCore_gml_GlobalScript_Emu_Core_3104_EmuCore_gml_GlobalScript_Emu_Core (line 107) -             if (_contents[| i]) _contents[| i].Render(at_x, at_y);
gml_Script_anon_EmuCore_gml_GlobalScript_Emu_Core_2870_EmuCore_gml_GlobalScript_Emu_Core (line 102) -         renderContents(x + base_x, y + base_y);
gml_Object_oCharSheet_Draw_64 (line 2) - EmuOverlay.Render();

**Comment by DragoniteSpam** [comment]
Variable was missing in a constructor, I'll have this fixed in an update soon-ish; quick fix is to define `self.own_entries = false;` in the `EmuList` constructor
